version: '2.2'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-my-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name : kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://node01:9200
    ports:
      - 5601:5601
    networks: 
      - elastic
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name : logstash
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - ELASTIC_HOST=http://node01:9200
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - "node01"
    command: logstash -f /etc/conf.d/logstash.conf
    volumes:
      - ./logstash.conf:/etc/conf.d/logstash.conf:ro
    networks: 
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge